kind: pipeline
type: docker
name: default
trigger:
  branch: master

steps:
  - name: golangci-lint
    image: golangci/golangci-lint:latest
    environment:
      GOOS: js
      GOARCH: wasm
    commands:
      - golangci-lint run ./wasm/
      - golangci-lint run ./server/

  - name: flake8
    image: pipelinecomponents/flake8:latest
    depends_on:
      - clone
    commands:
      - flake8
